spring.application.name=Attendly-app

spring.security.user.name=jerry
spring.security.user.password=jerry

spring.datasource.url=jdbc:postgresql://localhost:5432/Attendly
spring.datasource.username= postgres
spring.datasource.password=054jer_!